name: nikolajanke
favicon: null
layout_spectrum: 0.88749
typography_spectrum: 0.75517
title: Nikola Janke
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#714721'
    - '#9f754d'
    - '#572f0b'
    - '#d19c61'
    - '#e0b681'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
